### ISSUE TITLE
version 1.19.3  mod version 1.1.0

### ISSUE THREAD

**Issue by Iamkamin** [devs-immortal/bind-cmd#2] opened 2023-04-27 16:10 UTC
while  trying to do a key bind while still writing the comand and presing bound will crash minecraft ( tlauncher minecraft )

**Comment by kalucky0** [comment] 2023-04-27 16:18
Can you attach a crash report?

**Comment by kalucky0** [comment] 2023-11-06 01:18
I'm closing this issue as I'm unable to reproduce the bug

**Closed as not planned by kalucky0** 2023-11-06 01:18 UTC
Labels: bug
